In [3]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [0]:
%cd /content/gdrive/My \Drive
!mkdir spyfall
%cd spyfall
!git clone https://github.com/EdGartner/spyfall-bot.git
!mkdir gpt2
%cd gpt2
!git clone https://github.com/openai/gpt-2.git
%cd /content/gdrive/My \Drive/spyfall
!mv sample.py gpt-2/src # bc there was an issue in gpt-2 sample.py for me

In [0]:
%cd /content/gdrive/My \Drive/spyfall/gpt2/
!pip install -r requirements.txt
# will require restart

In [4]:
%tensorflow_version 1.x
import tensorflow as tf
import os
import json
from importlib import reload 
tf.__version__

TensorFlow 1.x selected.


'1.15.2'

In [0]:
%cd /content/gdrive/My \Drive/spyfall/gpt2
# !python download_model.py 355M
!python download_model.py 774M
# !python download_model.py 1558M

/content/gdrive/My Drive/spyfall/gpt2
Fetching checkpoint: 1.00kit [00:00, 729kit/s]                                                      
Fetching encoder.json: 1.04Mit [00:00, 35.4Mit/s]                                                   
Fetching hparams.json: 1.00kit [00:00, 579kit/s]                                                    
Fetching model.ckpt.data-00000-of-00001: 3.10Git [01:17, 39.9Mit/s]                                 
Fetching model.ckpt.index: 16.0kit [00:00, 8.82Mit/s]                                               
Fetching model.ckpt.meta: 1.38Mit [00:00, 41.1Mit/s]                                                
Fetching vocab.bpe: 457kit [00:00, 30.2Mit/s]                                                       


In [5]:
%cd /content/gdrive/My \Drive/spyfall
import spyfall_bot

/content/gdrive/My Drive/spyfall


In [0]:
prompts_text = ['Halfway through through the plane ride, the passengers began to feel restless.', 
                'It may have seemed like an ordinary morning at the local bank.',
                'The sun shone brightly, and the beach was packed with visitors.',
                'The lights dimmed, the curtains opened, and the audience fell silent as the Broadway show began.',
                'It is a busy Saturday night at the casio.']
spyfall_bot = reload(spyfall_bot)
bot = spyfall_bot.Bot(prompts_text, prompt_index=2, players=3, position=0, model_name='1558M')

In [0]:
transcript = ['Most people sit for hours in their chairs, exemplifying sedentary American culture.',
              'Some people go swimming, though.',
              'The waves are quite calm.',
              'There is a stand selling icecream.',
              'Naturally, it is quite overpriced.',
              'Seagulls wait eagerly for someone to drop their icecream.']

In [25]:
out = bot.generate(transcript, hide_info=0.1)
print(out)



One of the first things I noticed as I stepped into the dark and cold room was the lack of a door.


In [26]:
transcript.append(out)
transcript.extend(['Everyone seemed happy, just content to enjoy themselves.',
                   'But behind the sunny facade lurked a culture obsessed with body image and sex appeal.'])
print(bot.generate(transcript, hide_info=0.1))

'\n\n"I have a boyfriend," I said, "and I want to be with him.'

In [0]:
for i in range(1, len(transcript) + 1):
    print(bot.guess(transcript[:i], confidence=0.7))
    print(bot.saved)

In [10]:
print(bot.guess(['It was a little after 8:00 a.',
                 'Everyone seemed happy, just content to enjoy themselves.',
                   'But behind the sunny facade lurked a culture obsessed with body image and sex appeal.',
                 'The women were dressed in short skirts and tight tops, and the men in tight jeans and T-shirts.'], confidence=0.7))
print(bot.saved)

False
[0.22753683 0.09748875 0.5505031  0.1183204  0.00615091]


In [0]:
bot.close()

In [11]:
bot2 = spyfall_bot.Bot(prompts_text, prompt_index=None, players=6, position=5, model_name='1558M')

INFO:tensorflow:Restoring parameters from gpt2/models/1558M/model.ckpt


In [0]:
transcript2 = ['Everyone has stopped pretending to sleep.',
               'A few people scroll through the few movie options.',
               'It seems like everyone wants a stretch break.',
               'One man decided to go for a short jog and came back 10 minutes later.'
               'The line for the bathroom has become quite long.']

In [13]:
bot2.generate(transcript)

'\n\nThe first thing I noticed was the way the women were dressed.'

In [14]:
for i in range(1, len(transcript2) + 1):
    print(bot2.guess(transcript2[:i], confidence=0.7))
    print(bot2.saved)

False
[0.25845599 0.04037354 0.02950952 0.0356209  0.63604004]
False
[0.41176584 0.03988517 0.03103913 0.05590797 0.4614019 ]
False
[0.59089797 0.04512281 0.03851003 0.04997747 0.27549172]
False
[0.69590043 0.04301185 0.07210033 0.06866539 0.12032199]


In [27]:
bot2.index = 0
bot2.spy = False
transcript2.append('The first thing I noticed was the way the women were dressed.')
print(bot2.accuse(transcript2))
print(bot2.saved)

4
[1.4212767020070771, 1.3463997167417563, 1.6419682153393067, 1.216208755686229, 1.186758884489892, inf]


/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py:3335: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/usr/local/lib/python3.6/dist-packages/numpy/core/_methods.py:161: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)


In [0]:
bot2.close()